name: jumboconda
channels:
  - tufts
  - pytorch
  - conda-forge
platforms:
  - win-64
dependencies:
  - altair
  - astropy
  - beautifulsoup4
  - biopython
  - bokeh
  - cartopy
  - conda
  - contextily
  - cpuonly
  - csvkit
  - curl
  - dask
  - datashader
  - dill
  - earthengine-api
  - earthpy
  - eo-learn
  - featuretools
  - folium
  - gdal
  - geemap
  - gemgis
  - gensim
  - geocube
  - geojson
  - geopandas
  - geoplot
  - geopy
  - geosnap
  - geoviews
  - geowombat
  - git
  - graphviz
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - idle-shortcut # [win]
  - intake
  - intervaltree
  - ipympl >= 0.8.2
  - ipywidgets >= 8.0.1
  - jdcal
  - joblib
  - jupyter-resource-usage
  - jupyterlab 4.1.8
  - keplergl
  - laspy
  - leafmap
  - lidar
  - mamba
  - mapclassify
  - matplotlib
  - matplotlib-scalebar
  - mechanicalsoup
  - mesa
  - miniforge_console_shortcut >= 2.0 # [win]
  - mizani < 0.10
  - modin
  - momepy
  - movingpandas
  - mplleaflet
  - netcdf4
  - networkx
  - nltk
  - nodejs
  - numba < 0.57
  - numexpr
  - numpy
  - obspy
  - osmnx
  - pandana
  - pandas
  - pandoc
  - pillow
  - pingouin
  - pint
  - pip
  - plotly
  - plotnine
  - pomegranate
  - powershell-shortcut # [win]
  - proj
  - pseudonetcdf
  - psycopg2
  - pycaret
  - pycountry
  - pycurl
  - pydantic < 2.0
  - pygmt
  - pykrige
  - pymysql
  - pyodbc
  - pyppeteer
  - pyproj
  - pyqtgraph
  - pyrosar
  - pyrosm
  - pysal
  - pyshp
  - pysoundfile
  - pyspectral
  - pytables
  - python 3.11.*
  - pytorch
  - pyyaml
  - r5py
  - rasterio
  - rasterstats
  - regex
  - requests
  - retriever
  - richdem
  - rios
  - rioxarray
  - rsgislib
  - rtree
  - satpy
  - scikit-gstat
  - scikit-image
  - scikit-learn
  - scikit-mobility
  - scikit-optimize
  - scikit-spatial
  - scikit-surprise
  - scipy
  - seaborn
  - sentinelsat
  - sgkit
  - shapely
  - snorkel
  - spacy
  - sparse
  - spatialpandas
  - spectral
  - spyder-kernels
  - sqlalchemy
  - stateplane
  - statsmodels
  - streamz
  - sunpy
  - sympy
  - torchaudio
  - torchvision
  - tpot
  - urbanaccess
  - urbansim
  - urllib3
  - utm
  - vaex
  - verde
  - xarray
  - xarray-spatial
  - xgboost
  - yellowbrick
  - zarr
