Start-Process -FilePath "conda-lock"  -WindowStyle "Hidden" -Wait `
    -ArgumentList "render -k env conda-lock.yml"

$infile = "conda-win-64.lock.yml"
$outfile = "specs.txt"

New-Item -Path $outfile -ItemType "File" -Force | Out-Null
Add-Content -Path $outfile -Value "# generated by conda-lock"

Get-Content -Path $infile |
    Select-Object -Skip 1 -First 1 |
    Add-Content -Path $outfile

Get-Content -Path $infile |
    Select-Object -Skip 2 -First 1 |
    Add-Content -Path $outfile

$line = Get-Content -Path $infile |
    Select-String -Pattern "dependencies:"

(Get-Content -Path $infile).Replace( "  - ", "") |
    Select-Object -Skip $line.LineNumber |
    Sort-Object |
    Add-Content -Path $outfile

Remove-Item -Path $infile -Force
